---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.username}}
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/description: "Workspace Namespace"
    openshift.io/display-name: "Workspace"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.workbench}} 
  namespace: {{.Values.username}} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-{{.Values.username}}
  namespace: {{.Values.username}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{.Values.username}}
